sudo: required

services:
  - docker

before_install:
  - docker build -t svelte-neo4j-dev-image -f Dockerfile.dev .

script:
  - docker run svelte-neo4j-dev-image npm run validate

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  env: "Svelteneo4j-env-1"
  app: "svelte-neo4j"
  bucket_name: "elasticbeanstalk-ap-south-1-802769621610"
  bucket_path: "svelte-neo4j"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
