version: "3.7"

services:
  db:
    image: neo4j:4.2.1
    network_mode: bridge
    volumes:
      - $HOME/neo4j/data:/var/lib/neo4j/data
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/var/lib/neo4j/plugins
      - ./neo4j/logs:/var/lib/neo4j/logs
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${DB_USER}/${DB_PASSWORD}
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    network_mode: bridge
    ports:
      - "5000:5000"
      - "35729:35729"
    volumes:
      - .:/app
    depends_on:
      - db
