version: "3.7"

services:
  db:
    image: neo4j:4.2.1
    volumes:
      - $HOME/neo4j/data:/var/lib/neo4j/data
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/var/lib/neo4j/plugins
      - $HOME/neo4j/logs:/var/lib/neo4j/logs
    environment:
      - NEO4J_AUTH=${DB_USER}/${DB_PASSWORD}
  web:
    build:
      context: .
      args:
        - DB_URL=${DB_URL}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
    ports:
      - "8888:80"
    depends_on:
      - db
      - web
    restart: always
