version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    network_mode: bridge
    ports:
      - "5000:5000"
      - "35729:35729"
    volumes:
      - .:/app
  db:
    build:
      context: ./neo4j/
    network_mode: bridge
    ports:
      - "7474:7474"
      - "7687:7687"
